# Generated by Django 2.0.7 on 2018-11-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mNoteapp', '0002_auto_20181127_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('text', 'Tekst'), ('todo', 'To-do'), ('list', 'Lista')], default='text', max_length=5, verbose_name='Typ'),
        ),
    ]
