# Generated by Django 2.0.7 on 2018-12-11 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mNoteapp', '0004_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='Użytkownicy', to=settings.AUTH_USER_MODEL),
        ),
    ]
