# Generated by Django 2.0.7 on 2018-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mNoteapp', '0007_auto_20181214_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
