# Generated by Django 2.0.7 on 2018-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mNoteapp', '0008_note_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='private',
        ),
        migrations.AddField(
            model_name='note',
            name='groupId',
            field=models.IntegerField(default=0),
        ),
    ]
